name: CI/CD

on:
  push:
    branches:
     - "*"
    tags:
     - "*"

  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build X509 Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sslhep/x509-secrets
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "${GITHUB_REF##*/}"

